### ISSUE TITLE
Dependency conflict issue:  caused by multiple versions of com.fasterxml.jackson.core:jackson-databind:jar

### ISSUE THREAD

**Issue by LeoAugust19** [phiz71/vertx-swagger#102]
Hi, there are multiple versions of **com.fasterxml.jackson.core:jackson-databind:jar** in **io.swagger:petstore-vertx-json-rx-server:jar:1.0.0-SNAPSHOT**. As shown in the following dependency tree, based on "Maven's nearest wins strategy", only the older version **com.fasterxml.jackson.core:jackson-databind:jar:2.7.4:compile** will be loaded and the newer versions are shadowed, during the packaging process.

However, by static analysis method **<com.fasterxml.jackson.databind.ObjectMapper: java.lang.Object readValue(java.io.DataInput,java.lang.Class)>** only included in the shadowed com.fasterxml.jackson.core:jackson-databind:jar 2.9.3.  When your project invoking the missing method, an exception may be thrown.

### Dependency tree
io.swagger:petstore-vertx-json-rx-server:jar:1.0.0-SNAPSHOT
+- junit:junit:jar:4.12:test
|  \- org.hamcrest:hamcrest-core:jar:1.3:test
+- io.vertx:vertx-unit:jar:3.5.1:test
|  \- (io.vertx:vertx-core:jar:3.5.1:compile - scope updated from test; omitted for duplicate)
+- com.github.phiz71:vertx-swagger-router:jar:1.6.0:compile
|  +- io.vertx:vertx-core:jar:3.5.1:compile
|  |  +- io.netty:netty-common:jar:4.1.19.Final:compile
|  |  +- io.netty:netty-buffer:jar:4.1.19.Final:compile
|  |  |  \- (io.netty:netty-common:jar:4.1.19.Final:compile - omitted for duplicate)
|  |  +- io.netty:netty-transport:jar:4.1.19.Final:compile
|  |  |  +- (io.netty:netty-buffer:jar:4.1.19.Final:compile - omitted for duplicate)
|  |  |  \- (io.netty:netty-resolver:jar:4.1.19.Final:compile - omitted for duplicate)
|  |  +- io.netty:netty-handler:jar:4.1.19.Final:compile
|  |  |  +- (io.netty:netty-buffer:jar:4.1.19.Final:compile - omitted for duplicate)
|  |  |  +- (io.netty:netty-transport:jar:4.1.19.Final:compile - omitted for duplicate)
|  |  |  \- io.netty:netty-codec:jar:4.1.19.Final:compile
|  |  |     \- (io.netty:netty-transport:jar:4.1.19.Final:compile - omitted for duplicate)
|  |  +- io.netty:netty-handler-proxy:jar:4.1.19.Final:compile
|  |  |  +- (io.netty:netty-transport:jar:4.1.19.Final:compile - omitted for duplicate)
|  |  |  +- io.netty:netty-codec-socks:jar:4.1.19.Final:compile
|  |  |  |  \- (io.netty:netty-codec:jar:4.1.19.Final:compile - omitted for duplicate)
|  |  |  \- (io.netty:netty-codec-http:jar:4.1.19.Final:compile - omitted for duplicate)
|  |  +- io.netty:netty-codec-http:jar:4.1.19.Final:compile
|  |  |  \- (io.netty:netty-codec:jar:4.1.19.Final:compile - omitted for duplicate)
|  |  +- io.netty:netty-codec-http2:jar:4.1.19.Final:compile
|  |  |  +- (io.netty:netty-codec-http:jar:4.1.19.Final:compile - omitted for duplicate)
|  |  |  \- (io.netty:netty-handler:jar:4.1.19.Final:compile - omitted for duplicate)
|  |  +- io.netty:netty-resolver:jar:4.1.19.Final:compile
|  |  |  \- (io.netty:netty-common:jar:4.1.19.Final:compile - omitted for duplicate)
|  |  +- io.netty:netty-resolver-dns:jar:4.1.19.Final:compile
|  |  |  +- (io.netty:netty-resolver:jar:4.1.19.Final:compile - omitted for duplicate)
|  |  |  +- io.netty:netty-codec-dns:jar:4.1.19.Final:compile
|  |  |  |  \- (io.netty:netty-codec:jar:4.1.19.Final:compile - omitted for duplicate)
|  |  |  \- (io.netty:netty-transport:jar:4.1.19.Final:compile - omitted for duplicate)
|  |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.9.3:compile - omitted for conflict with 2.7.4)
|  |  \- **(com.fasterxml.jackson.core:jackson-databind:jar:2.9.3:compile - omitted for conflict with 2.7.4)**
|  +- io.vertx:vertx-rx-java:jar:3.5.1:compile
|  |  +- io.reactivex:rxjava:jar:1.3.5:compile
|  |  \- (io.vertx:vertx-core:jar:3.5.1:compile - omitted for duplicate)
|  +- io.vertx:vertx-web:jar:3.5.1:compile
|  |  +- io.vertx:vertx-auth-common:jar:3.5.1:compile
|  |  |  \- (io.vertx:vertx-core:jar:3.5.1:compile - omitted for duplicate)
|  |  +- io.vertx:vertx-bridge-common:jar:3.5.1:compile
|  |  \- (io.vertx:vertx-core:jar:3.5.1:compile - omitted for duplicate)
|  \- io.swagger:swagger-parser:jar:1.0.26:compile
|     +- io.swagger:swagger-core:jar:1.5.12:compile
|     |  +- org.apache.commons:commons-lang3:jar:3.2.1:compile
|     |  +- (org.slf4j:slf4j-api:jar:1.6.3:compile - omitted for duplicate)
|     |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.8.4:compile - omitted for conflict with 2.9.0)
|     |  +- **(com.fasterxml.jackson.core:jackson-databind:jar:2.8.4:compile - omitted for conflict with 2.9.3)**
|     |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.8.4:compile
|     |  |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.8.4:compile - omitted for conflict with 2.9.3)
|     |  |  \- org.yaml:snakeyaml:jar:1.15:compile
|     |  +- io.swagger:swagger-models:jar:1.5.12:compile
|     |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.8.4:compile - omitted for conflict with 2.9.0)
|     |  |  +- (org.slf4j:slf4j-api:jar:1.6.3:compile - omitted for duplicate)
|     |  |  \- io.swagger:swagger-annotations:jar:1.5.12:compile
|     |  +- com.google.guava:guava:jar:18.0:compile
|     |  \- javax.validation:validation-api:jar:1.1.0.Final:compile
|     +- org.slf4j:slf4j-ext:jar:1.6.3:compile
|     |  +- (org.slf4j:slf4j-api:jar:1.6.3:compile - omitted for duplicate)
|     |  \- ch.qos.cal10n:cal10n-api:jar:0.7.4:compile
|     +- org.slf4j:slf4j-api:jar:1.6.3:compile
|     \- commons-io:commons-io:jar:2.4:compile
\- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.7.4:compile
   +- com.fasterxml.jackson.core:jackson-core:jar:2.7.4:compile
   \- **com.fasterxml.jackson.core:jackson-databind:jar:2.7.4:compile**
      +- com.fasterxml.jackson.core:jackson-annotations:jar:2.7.0:compile
      \- (com.fasterxml.jackson.core:jackson-core:jar:2.7.4:compile - omitted for duplicate)

### Solution
Upgrade jackson-datatype-jsr310 to 2.9.3.

Thanks!

Regards,
Leo

**Comment by LeoAugust19** [comment]
@phiz71 May I pull a request to fix this issue?

**Comment by LeoAugust19** [comment]
@philippkumar Hi, the above information is abtained based on static analysis. Do you further information to confirm it's a bug? I can try to provide you more.

**Comment by LeoAugust19** [comment]
### Stack trace

Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.readValue(Ljava/io/DataInput;Ljava/lang/Class;)Ljava/lang/Object;
	at io.vertx.core.json.Json.decodeValue(Json.java:165)
	at io.vertx.core.json.JsonObject.fromBuffer(JsonObject.java:952)
	at io.vertx.core.json.JsonObject.<init>(JsonObject.java:72)

**Comment by LeoAugust19** [comment]
@inikolaev, Could you please help me review this issue?
